// <auto-generated />
using Burger_app.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Burger_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Burger_app.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sides"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("Burger_app.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Burgers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Beef, cheddar, pickles",
                            Name = "Classic stack",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Two patties, double cheese",
                            Name = "Double smash",
                            Price = 11.49m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Buttermilk fried, slaw, mayo",
                            Name = "Crispy chicken",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Cheese sauce, jalapeños",
                            Name = "Loaded fries",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Thick, hand-spun",
                            Name = "Vanilla shake",
                            Price = 4.99m
                        });
                });

            modelBuilder.Entity("Burger_app.Models.MenuItem", b =>
                {
                    b.HasOne("Burger_app.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
